name: pdf-frame-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - transformers==4.51.3
      - accelerate==1.6.0
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - huggingface_hub==0.30.2
      - bitsandbytes==0.45.5
      - peft==0.15.2
      - datasets==3.5.0
      - trl==0.16.1
      - fastapi==0.110.0
      - uvicorn==0.27.1
      - pydantic==2.6.3
      - torch==2.2.1
      - numpy==1.26.4
      - tqdm==4.66.2
